version: '3.7'
services:
    api:
        build: . 
        volumes:
            - .:/go/src/jr-game
        ports: 
            - 8080:8080
        working_dir: /go/src/jr-game
        command: go run cmd/main.go
    app:
        build: ./app
        volumes:
            - ./app:/usr/share/nginx/html
        ports:
            - 80:80
        working_dir: /usr/share/nginx/html

