version: '3.7'
services:
    app:
        build: .
        volumes:
            - .:/go/src/jr-game
        ports: 
            - 80:8080
        working_dir: /go/src/jr-game/cmd
        command: > 
            sh -c "go get && go run socket.go"




