version: '3.7'
services:
    app:
        build: .
        volumes:
            - .:/go/src/jr-game
        ports: 
            - 80:80
        working_dir: /go/src/jr-game
        command: go run cmd/main.go

